# Generated by Django 5.1.6 on 2025-02-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(default='kkleinikov', max_length=16, verbose_name='Created by')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('modified_by', models.CharField(max_length=16, null=True, verbose_name='Last updated by')),
                ('note', models.TextField(verbose_name='Note')),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=30, verbose_name='Short Description')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='ISO')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
    ]
