# Generated by Django 5.1.6 on 2025-02-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='numeric_code',
            field=models.PositiveIntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='modified_by',
            field=models.CharField(max_length=16, null=True, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='note',
            field=models.TextField(null=True, verbose_name='Note'),
        ),
    ]
