# Generated by Django 5.1.6 on 2025-02-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_currency_numeric_code_alter_currency_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='numeric_code',
            field=models.PositiveIntegerField(max_length=999, null=True),
        ),
    ]
