# Generated by Django 5.1.6 on 2025-02-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_currency_numeric_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='numeric_code',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
