# Generated by Django 5.1.6 on 2025-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_currency_numeric_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_by',
            field=models.CharField(max_length=16, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='modified_by',
            field=models.CharField(blank=True, default='kkleinikov', max_length=16, verbose_name='Last modified by'),
            preserve_default=False,
        ),
    ]
