# Generated by Django 3.2.16 on 2025-04-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_currency_created_by_alter_currency_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=16, verbose_name='Created by')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('modified_by', models.CharField(blank=True, max_length=16, verbose_name='Last modified by')),
                ('rate_date', models.DateField()),
                ('nominal', models.PositiveSmallIntegerField(default=1)),
                ('rate', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='common.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['-rate_date', 'currency'],
                'unique_together': {('currency', 'rate_date')},
            },
        ),
    ]
